### ISSUE TITLE
BESSPIN-GFE  with latest Flute

### ISSUE THREAD

**Issue by rgollap1** [GaloisInc/BESSPIN-GFE#4]
Can the BESSPIN-GFE be used with latest version of bluespec Flute ? if yes , what changes are needed. Please Advice

**Comment by kiniry** [comment]
It is likely nearly a drop-in replacement.   The Bluespec guys would have a good feel for this.  I'll ask Nikhil to reflect.

**Comment by rgollap1** [comment]
ok will contact bluespec, thank you

**Comment by kiniry** [comment]
They'll probably jump in this issue to comment.  I already pinged them.

**Comment by rgollap1** [comment]
An update on this, i actually tried to boot it with the latest version of Flute with write back caches  and succeeded in booting it with busy box , but there seems to be a problem with openocd.

When gcc try to connect to openocd , it is timing out and fails and this seems to be random , the error is the following

Error: DMI operation didn't complete in 2 seconds. The target is either really slow or broken. You could increase the timeout with riscv set_command_timeout_sec.

we tried with increased timeout, but still same issue and this happens randomly .

Sometime it just boots up normally, but most of the times it timeouts. Any idea on what could cause the openocd timeout

**Comment by kiniry** [comment]
Thanks for that information.  I received an update this morning on the new work that makes this architecture standardized across the deployment of the GFE on the VCU118 vs. on AWS F1 (a project called AWSteria that will be open sourced too).  Nikhil now has it cleaned up and running Flute on both deployment platforms and we should soon also see the other Bluespec CPUs working therein.

**Comment by rgollap1** [comment]
That is perfect  and thanks for the update
